### PR TITLE
Php7

### PR DESCRIPTION
**Pull request by Infern1**
### Changes proposed in this pull request:
- PHP7 Provision
-
-

Fixes # .

Checklist:
- [ ] docs up-to-date

### CODE REVIEW

**Comment by msimerson** [comment]
this branch needs to be merged or rebased from master so that I can merge it.

**Comment by Infern1** [comment]
Can you give some guidance here? Thought this would be the proper way.

**Comment by Infern1** [comment]
now should be ok if I'm right

**Comment by msimerson** [comment]
Yup, all good. Thanks.

**Pull request merged**
