### PR TITLE
Adding ftp-proxy support

### PR DESCRIPTION
**Pull request by Infern1**
During install vpopmail jail cpan is trying to get some data via ftp and fails

### Changes proposed in this pull request:
- Add ftp-proxy to pf.conf
- Start ftp-proxy
-

Fixes # .
downloading cpan

### CODE REVIEW

**Comment by msimerson** [comment]
Thoughts:
* with an internet moving towards TLS everywhere, it seems ill advised to deploy archaic protocols like active FTP by default. Maybe as an option?
* I actually prefer that the FTP connections fail and that HTTP urls are used instead
* there's likely [a better way](http://perl-begin.org/topics/cpan/life-with-cpan/) to configure CPAN* and and avoid the timeout(s), depending on what exactly is failing

**Comment by msimerson** [comment]
* if CPAN/CPANPLUS/cpanminus are savage beasts that refuse to be tamed, another option could be enabling the ftp proxy during the install section(s) that need it and then disabling it after.

**Comment by Infern1** [comment]
I agree that old style FTP is not really wanted anymore. Finding a better method than using ftp-proxy has my support.
However I implemented this, since I hate waiting during the provision... takes ages before cpan times out during install of Qmail-Delivered. I think this the only one which is really the problem

**Comment by msimerson** [comment]
Maybe cpanm is smarter about it. Can you try this locally?

```diff
diff --git a/qmail/run.sh b/qmail/run.sh
index 54421fc..dbd5ebd 100644
--- a/qmail/run.sh
+++ b/qmail/run.sh
@@ -383,8 +383,8 @@ EO_DELIVERABLED_RUN
        pkg install -y p5-Package-Constants
 
        echo "installing Qmail::Deliverable"
-       pkg install -y p5-Log-Message p5-Archive-Extract p5-Object-Accessor p5-Module-Pluggable p5-CPANPLUS
-       perl -MCPANPLUS -e 'install Qmail::Deliverable'
+       pkg install -y p5-Log-Message p5-Archive-Extract p5-Object-Accessor p5-Module-Pluggable p5-App-Cpanminus
+       cpanm Qmail::Deliverable
 }
 
 install_qmail_chkuser()
```

**Comment by msimerson** [comment]
I didn't read enough source for CPANPLUS to see but this might also work:

```diff
diff --git a/qmail/run.sh b/qmail/run.sh
index 54421fc..b4482e6 100644
--- a/qmail/run.sh
+++ b/qmail/run.sh
@@ -384,7 +384,7 @@ EO_DELIVERABLED_RUN
 
        echo "installing Qmail::Deliverable"
        pkg install -y p5-Log-Message p5-Archive-Extract p5-Object-Accessor p5-Module-Pluggable p5-CPANPLUS
-       perl -MCPANPLUS -e 'install Qmail::Deliverable'
+       env FTP_PASSIVE=1 perl -MCPANPLUS -e '$ENV{FTP_PASSIVE}=1; install Qmail::Deliverable'
 }
 
 install_qmail_chkuser()
```

**Comment by Infern1** [comment]
downside the run script is fetched from git every time the script is running... not easy to test

**Comment by msimerson** [comment]
That's not too hard to work around:

```diff
diff --git a/mail-toaster.sh b/mail-toaster.sh
index 76bacb9..7afb273 100755
--- a/mail-toaster.sh
+++ b/mail-toaster.sh
@@ -1008,7 +1008,7 @@ mt6-include()
                mkdir include || exit
        fi
 
-       fetch -m -o "include/$1.sh" "$TOASTER_SRC_URL/include/$1.sh"
+       #fetch -m -o "include/$1.sh" "$TOASTER_SRC_URL/include/$1.sh"
 
        if [ ! -f "include/$1.sh" ]; then
                echo "unable to download include/$1.sh"
```

**Comment by Infern1** [comment]
this fix seems to work
- stopped ftp-proxy
- tried to provision vpopmail
=> no timeout, runs as expected

**Pull request closed without merging**
