### PR TITLE
CI testing via GitLab

### PR DESCRIPTION
**Pull request by msimerson**
### Changes proposed in this pull request:
- adds GitLab CI testing
    - using gitlab-runners + ssh executor
    - to a remote FreeBSD server (I run inside vmware)
- I use [gitlab.com](https://gitlab.com) (no maintenance) but this includes setup for local GitLab
- I install gitlab runners on my workstation (Mac OS X)
    - alternatively, this includes a gitlab runner jail for FreeBSD
- switch pkg from quarterly -> latest

Checklist:
- [ ] docs up-to-date

### CODE REVIEW

**Comment by Infern1** [comment]
Why not go for gitea or gogs? Not as bloated as gitlab and fulfills the job most of the time.

**Comment by msimerson** [comment]
I don't want GitLab or gitea or gogs. They are merely a means to an end. What I want is smarter CI for this repo. Right now, all I have is lint tests. I have to perform all the build tests manually. I want automated tests that spins up a FreeBSD VM, builds a complete mail toaster, runs all the integration tests, and sends the response back to the GitHub API with a thumbs up when the tests pass.

I may never merge this PR, but I'm experimenting with docker-freebsd and gitlab-runner on FreeBSD 11. If I can get them working reasonably well, then I have a solution that should be less work to maintain than just slinging a bunch more bash at the problem.

**Comment by Infern1** [comment]
Ah that makes sense, having proper tests in place would be a huge improvement

**Comment by msimerson** [comment]
Getting Docker running on FreeBSD wasn't difficult since it's in ports (docker-freebsd). But it's a crusty old version from 2015 and seems abandoned. But I charged ahead and spun up a Docker with FreeBSD and it works well enough! But, all the ZFS magic happens **outside** the docker, and there's no zpools inside the docker. That drained all the air out of that balloon.

Then I tried running Docker on my desktop Mac (a 1st tier platform) to create an environment for the [GitLab Runner](https://docs.gitlab.com/runner/commands/README.html). I used docker-machine with the vmware driver and headed down that road thinking perhaps I'd deploy gitlab-runner within the VM, snapshot it, and then use the the Shell or Exec executor to deploy into the same VM as the Runner. That works, but then there's user management issues as the runner is unprivileged and the build obviously requires root, and dancing with sudo. Blech.

What I've settled on is just installing the GitLab runner on my Mac. I've created [a wiki page](https://github.com/msimerson/Mail-Toaster-6/wiki/Develop-CI-Testing) lightly documenting it. In short, the runner makes a SSH connection to a VM and then kicks off the build cycle within the VM. I've added a script to `./tests/` that I use to revert the VM after a test cycle. 

It works. I'm ready to merge, but I'd appreciate a second set of eyes, and perhaps a test run.

**Comment by msimerson** [comment]
What the interface looks like:

gitlab runner

**Pull request merged**
